packages:
  common: !include common.yaml

esphome:
  name: light

canopen:
  id: can_open
  node_id: 7
  entities:
    - index: 1
      id: light1
      tpdo: 0

    - index: 2
      id: light2
      tpdo: 0

output:
  - platform: template
    id: cw_output1
    type: float
    write_action:
      - logger.log:
          format: "output1: %f"
          args: ['state']

  - platform: template
    id: ww_output1
    type: float
    write_action:
      - logger.log:
          format: "output2: %f"
          args: ['state']

  - platform: template
    id: cw_output2
    type: float
    write_action:
      - logger.log:
          format: "output1: %f"
          args: ['state']

  - platform: template
    id: ww_output2
    type: float
    write_action:
      - logger.log:
          format: "output2: %f"
          args: ['state']

light:
  - platform: cwww
    id: light1
    name: "1"
    cold_white: cw_output1
    warm_white: ww_output1
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    default_transition_length: 0s

  - platform: cwww
    id: light2
    name: "2"
    cold_white: cw_output2
    warm_white: ww_output2
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    default_transition_length: 0s
