name: "Test"

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure
        run: framework_type=esp-idf framework_version=4.4.8 framework_platform_version=5.4.0 envsubst < test/common.yaml.template > test/common.yaml
      - name: Compile
        uses: esphome/build-action@v4.0.4
        id: esphome-build
        with:
          yaml-file: test/esp32_c3.yaml

