name: "Test"

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4.2.2
      - name: Compile
        uses: esphome/build-action@v4.0.4
        id: esphome-build
        with:
          yaml-file: test/esp32_c3.yaml

